### ISSUE TITLE
Diagrama de sequência: UC20 Publicar programa

### ISSUE THREAD

**Issue by ViniciusAS** [SamuelBFavarin/runplace#3]
UC20 Publicar programa

**Comment by croisebeck** [comment]
#partiu

**Comment by sarahborini** [comment]
![publicar_programa](https://user-images.githubusercontent.com/27982530/33517539-460ea28a-d76d-11e7-8277-2715b4008e6e.jpg)

**Comment by sarahborini** [comment]
Boa tarde,

Segue arquivo.

Atenciosamente,
Sarah Borini.
