### ISSUE TITLE
Diagrama de sequência: UC16 Visualizar Coleção de Programas

### ISSUE THREAD

**Issue by ViniciusAS** [SamuelBFavarin/runplace#4]

**Comment by sarahborini** [comment]
![visualiza_colecao](https://user-images.githubusercontent.com/27982530/33517183-93f0c840-d766-11e7-8ee0-0bcaf18cddbb.jpg)

**Comment by sarahborini** [comment]
Boa tarde,

Segue arquivo.

Atenciosamente,
Sarah Borini.
