### ISSUE TITLE
Diagrama de sequência: UC09 Realizar download do Software

### ISSUE THREAD

**Issue by ViniciusAS** [SamuelBFavarin/runplace#5]

**Comment by SamuelBFavarin** [comment]
Para dar uma adiantada, vamos fazer esse diagrama

**Comment by SamuelBFavarin** [comment]
Terminado 
[diagrama_sequencia_download.pdf](https://github.com/SamuelBFavarin/runplace/files/1508054/diagrama_sequencia_download.pdf)

**Comment by SamuelBFavarin** [comment]
Aprovado pela Professora :+1:

**Comment by croisebeck** [comment]
Padrão Qualyteam de qualidade. kkkkk
